services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"